import { Vector2 } from "../classes/Vector2.js";

export const map_expedition = {

    entityData: {
        player: {
            cellCoord: new Vector2(null, null),
            isFacing: 'Up',
        },
        gary: {
            cellCoord: new Vector2(null, null),
            isFacing: 'Up',
        },
        fred: {
            cellCoord: new Vector2(null, null),
            isFacing: 'Up',
        },
        george: {
            cellCoord: new Vector2(null, null),
            isFacing: 'Up',
        },
        harold: {
            cellCoord: new Vector2(null, null),
            isFacing: 'Up',
        },
    },

    floors: [
        {
            match: 'water',
            imageName: 'water',
            auto: false,
            z: 0,
            layout:
                `   wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwwwwww`,
        },
        {
            match: 'sand',
            imageName: 'sandPure',
            auto: true,
            z: 0,
            layout:
                `   ...................
                    ...................
                    ......ssssssssss...
                    ......ssssssssss...
                    ......ssssssssss...
                    ......ssssssssss...
                    ......ssssssssss...
                    ......ssssssssss...
                    ......ssssssssss...
                    ......ssssssssss...
                    ...................
                    ...................`,
        },
        {
            match: 'dirt',
            imageName: 'dirtSand',
            auto: true,
            z: 0,
            layout:
                `   ...................
                    ...................
                    ...................
                    .......dddddddd....
                    .......dddddddd....
                    .......dddddddd....
                    .......dddddddd....
                    .......dddddddd....
                    .......dddddddd....
                    ...................
                    ...................
                    ...................`,
        },
        {
            match: 'road',
            imageName: 'stoneDirt',
            auto: true,
            z: 0,
            layout:
                `   ...................
                    ...................
                    ...................
                    ...................
                    ........rrrrrr.....
                    ........r....r.....
                    ........r....r.....
                    ........rrrrrr.....
                    ...................
                    ...................
                    ...................
                    ...................`,
        },
    ],
    occupants:
        `   ...................
            ...................
            ...................
            ...................
            ..........01.......
            ............2......
            ..........P........
            ...................
            ...................
            .....B.............
            ...................
            ...................`,
}