export const map_2 = {
    paths:
    `   ........................
        ........................
        .p......................
        .pppppp......pppp.......
        ......p....ppp..p.......
        ......p....p....pp......
        ......p....p.....p......
        ......pppppp.....p......
        ................pp......
        ................p.......
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................`,

    floor:
    `   GGGGggddrrddGGGGGGdswwww
        GGGGggddrrddGGGGGGdswwww
        ggGgggddrrddGGGGGGdswwww
        gggggdddrrddGGGGGGdswwww
        GGGGggddrrddGGGGGGdswwww
        GGggggddrrddGGGGGGdswwww
        Ggggggdrrrdgggggggdswwww
        Ggggggdrrddgggggggdsswww
        Ggggggdrrddgggggggsswwww
        Ggggggdrrdddgggggggsswww
        Ggggggdrrrddggggggssswww
        Ggwwggddrrddggggggssssww
        ggwwwgddrrddggggggssssww
        ggwwggddrrddgggggggsssww
        gggggddrrrddggggggggssww
        gggggddrrddggggggggggssw
        gggggddrrddgggggggggggsw
        gggggddrrddgggggsgddddss
        gggggdrrddgggggsssddddds
        gggggdrrddgggsssssssddds
        gggggdrrddgggswwswwsssss
        gggggdrrddggsswwswwwwwww
        gggggdrrddggswwwswwwwwww
        gggggdrrGdggsswwswwwssww
        gggggGrGGdggswwwswwssssw
        gggggGrGGdggswwwswwsssww
        gggggGrGddggswwwssssswww
        gggggGwGdgggsswwwwwwwwws`,
    occupants: 
    `   tTTT...........tt.......
        tTTT...........tttt.....
        t.T........tt....tt.....
        t..........tt...........
        ttTT..........tt........
        ttP.....03..tttt........
        t...........tt..........
        t..............tt.......
        2.............tttt......
        t.............tttt......
        t..............tt.......
        T..............tt.......
        T.......................
        ........................
        ........................
        ........................
        ....T......T...t.t......
        ...............t.t......
        ..T........T............
        .....T..TT..............
        .....T..TT..............
        .....T..TT..............
        .....T...T..............
        .....T...T..........1...
        .....T..TT.........i..a.
        .....T.TT...............
        .....T.T................
        .....T.T................
        .....TET................`,




};