export const map_2 = {
    paths:
    `   ........................
        ......p.................
        ......p.................
        ......p......pppp.......
        ......p....ppp..p.......
        ......p....p....pp......
        ......p....p.....p......
        ......pppppp.....p......
        ................pp......
        ................p.......
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................`,

    floor:
    `   dddGGGGdrrddGGGGGGdswwww
        dddGGGGdrrddGGGGGGdswwww
        dddGGGGdrrddGGGGGGdswwww
        GGGGGGGdrrddGGGGGGdswwww
        GGGGGGGdrrddGGGGGGdswwww
        GGggggddrrddGGGGGGdswwww
        Ggggggdrrrdgggggggdswwww
        Ggggggdrrddgggggggdsswww
        Ggggggdrrddgggggggsswwww
        Ggggggdrrdddgggggggsswww
        Ggggggdrrrddggggggssswww
        Ggwwggddrrddggggggssssww
        ggwwwgddrrddggggggssssww
        ggwwggddrrddgggggggsssww
        gggggddrrrddggggggggssww
        gggggddrrddggggggggggssw
        gggggddrrddgggggggggggsw
        gggggddrrddgggggsgddddss
        gggggdrrddgggggsssddddds
        gggggdrrddgggsssssssddds
        gggggdrrddgggswwswwsssss
        gggggdrrddggsswwswwwwwww
        gggggdrrddggswwwswwwwwww
        gggggdrrGdggsswwswwwssww
        gggggGrGGdggswwwswwssssw
        gggggGrGGdggswwwswwsssww
        gggggGrGddggswwwssssswww
        gggggGwGdgggsswwwwwwwwws`,
    occupants: 
    `   ...............tt.......
        tt.............tttt.....
        tt.........tt....tt.....
        ..TT.......tt...........
        ttTT..........tt........
        tt......03..tttt........
        t...........tt..........
        t..............tt.......
        2.............tttt......
        t.............tttt......
        t..............tt.......
        T..............tt.......
        T...............P.......
        ........................
        ........................
        ........................
        ....T......T...t.t......
        ...............t.t......
        ..T........T............
        .....T..TT..............
        .....T..TT..............
        .....T..TT..............
        .....T...T..............
        .....T...T..........1...
        .....T..TT.........i..a.
        .....T.TT...............
        .....T.T................
        .....T.T................
        .....TET................`,




};