import { Vector2 } from "../classes/Vector2.js";

export const map_expedition = {

    entityData: {
        player: {
            cellCoord: new Vector2(null, null),
            isFacing: 'up',
        },
        gary: {
            cellCoord: new Vector2(null, null),
            isFacing: 'up',
        },
        fred: {
            cellCoord: new Vector2(null, null),
            isFacing: 'up',
        },
        george: {
            cellCoord: new Vector2(null, null),
            isFacing: 'up',
        },
        harold: {
            cellCoord: new Vector2(null, null),
            isFacing: 'up',
        },
    },

    floors: [
        {
            match: 'water',
            imageName: 'water',
            auto: false,
            z: 0,
            layout:
                `   wwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwww
                    www..........www
                    www..........www
                    www..........www
                    www..........www
                    www..........www
                    www..........www
                    www..........www
                    www..........www
                    wwwwwwwwwwwwwwww
                    wwwwwwwwwwwwwwww`,
        },
        {
            match: 'grass2',
            imageName: 'grass2',
            auto: false,
            z: 0,
            layout:
                `   ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................`,
        },
        {
            match: null,
            auto: false,
            z: 0,
            layout:
                `.`,
        },
        {
            match: null,
            auto: false,
            z: 0,
            layout:
                `.`,
        },
        {
            match: 'dirt',
            imageName: 'dirtSand',
            auto: true,
            z: 0,
            layout:
                `   ................
                    ................
                    ...dddddddddd...
                    ...dddddddddd...
                    ...dddddddddd...
                    ...dddddddddd...
                    ...dddddddddd...
                    ...dddddddddd...
                    ...dddddddddd...
                    ...dddddddddd...
                    ................
                    ................`,
        },
        {
            match: 'road',
            imageName: 'stoneDirt',
            auto: true,
            z: 0,
            layout:
                `   ................
                    ................
                    ................
                    ....rrrrrrrr....
                    ....rrrrrrrr....
                    ....rr....rr....
                    ....rr....rr....
                    ....rrrrrrrr....
                    ....rrrrrrrr....
                    ................
                    ................
                    ................`,
        },
    ],
    occupants:
        `   ................
            ................
            ................
            ................
            .......01.......
            .........2......
            .......P........
            ................
            ................
            ................
            ...X............
            ................`,
}